### ISSUE TITLE
Add `posix-fdtab` internal library for file descriptor abstraction

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#570] opened 2022-10-05 02:59 UTC
### Feature request summary

The `posix-fdtab` internal library will provide the file descriptor abstraction. A file descriptor table will be provided per-thread, if cloned that way.

The library will provide the interface to register the syscalls that you can have with any file descriptor (`read`, `write`, `close`, etc.).

The file descriptor constructor syscalls (`open`, `socket`, `eventfd`, etc.) will be provided by the according subsystem libraries (e.g, `vfscore`, `posix-socket`).

**Comment by nderjung** [comment] 2022-11-22 11:51
Closing as duplicate of #52.

**Closed as completed by nderjung** 2022-11-22 11:51 UTC
Labels: kind/enhancement, area/lib, new/primitive
