### ISSUE TITLE
binary-compat: php: Cannot handle multiple user space heaps

### ISSUE THREAD

**Issue by MathVerg** [unikraft/unikraft#611] opened 2022-10-23 15:19 UTC
### Describe the bug

This issue occurred when trying to run the PHP static PIE (see PR https://github.com/unikraft/static-pie-apps/pull/78)

### Steps to reproduce

In a setup with static-apps :
```
./run_efloader -d ../static-pie-apps/php/php
```

### Expected behavior

I expected the unikernel to boot and print "Hello world!" from the PHP interpreter.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
SeaBIOS (version 1.16.0-debian-1.16.0-4)
Booting from ROM..Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
            Mimas 0.7.0~1e17a9c8-custom
[    0.339465] CRIT: [appelfloader] <brk.c @   27> Cannot handle multiple user space heaps: Not implemented!
[    0.343955] CRIT: [appelfloader] <brk.c @   44> Failed to increase heap: Not implemented!

munmap() failed: [12] Cannot allocate memory

munmap() failed: [12] Cannot allocate memory
Fatal glibc error: malloc assertion failure in sysmalloc: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long)
```

**Comment by razvand** [comment] 2022-10-23 15:22
5 hackathon points

**Comment by i-Pear** [comment] 2023-04-01 10:13
Same things at https://github.com/unikraft/static-pie-apps/pull/85.

The first error "Cannot handle multiple user space heaps: Not implemented!" is caused by calling brk(NULL) twice.

The first call comes from:
```
#0  0x00007ffff5333f5b in _dl_early_allocate ()
#1  0x00007ffff527513a in __libc_setup_tls ()
#2  0x00007ffff52742ab in __libc_start_main_impl ()
#3  0x00007ffff4803255 in _start ()
```

And the second is from:
```
#0  0x00007ffff53043eb in brk ()
#1  0x00007ffff530449f in sbrk ()
#2  0x00007ffff52b7140 in sysmalloc ()
#3  0x00007ffff52b8491 in _int_malloc ()
#4  0x00007ffff52b8635 in tcache_init.part ()
#5  0x00007ffff52b8e74 in __malloc ()
#6  0x00007ffff532cdfb in _dl_get_origin ()
#7  0x00007ffff5335977 in _dl_non_dynamic_init ()
#8  0x00007ffff53377f9 in __libc_init_first ()
#9  0x00007ffff5274323 in __libc_start_main_impl ()
#10 0x00007ffff4803255 in _start ()
```

There's no multi-process between the two brk(NULL). When executing in linux, it only needs to return the result of the previous brk() in the second call, which is just a simple query.

**Comment by andraprs** [comment] 2023-05-16 08:49
PR https://github.com/unikraft/app-elfloader/pull/15, that contains updates for the "brk" codebase, has been merged.

Please reopen the GitHub issue if additional changes are needed. Thank you.

**Closed as completed by andraprs** 2023-05-16 08:49 UTC
Labels: kind/bug, topic/mm, kind/hackathon
