### ISSUE TITLE
Double fault at context switch when making elfloader with posix-mmap and lwip

### ISSUE THREAD

**Issue by John-Ted** [unikraft/unikraft#787] opened 2023-03-08 12:09 UTC
### Describe the bug

When running an elfloader image created using posix-mmap and lwip, it crashes with a double fault at a [context switch](https://github.com/unikraft/unikraft/blob/staging/arch/x86/x86_64/ctx.S#L92) when operating on a semaphore inside [liblwip_init](https://github.com/unikraft/lib-lwip/blob/staging/init.c#L163).

### Steps to reproduce

1. Create an elfloader image using posix-mmap and lwip.
2. Try to run an application in binary compat mode using the image created at step 1.

Example config:
[config_lwip.txt](https://github.com/unikraft/unikraft/files/10920404/config_lwip.txt)

### Expected behavior

The unikernel should boot, output the banner, enter the application's main function and any possible issues should arise due to the binary application, not the unikernel itself.

### Relevant log output

```shell
SeaBIOS (version 1.15.0-1)
Booting from ROM...
[    0.100039] dbg:  [libvfscore] <main.c @ 1990> (int) uk_syscall_r_dup2((int) 0x0, (int) 0x1)
[    0.101362] dbg:  [libvfscore] <main.c @ 1937> (int) uk_syscall_r_dup3((int) 0x0, (int) 0x1, (int) 0x0)
[    0.102799] dbg:  [libvfscore] <main.c @ 1990> (int) uk_syscall_r_dup2((int) 0x0, (int) 0x2)
[    0.104090] dbg:  [libvfscore] <main.c @ 1937> (int) uk_syscall_r_dup3((int) 0x0, (int) 0x2, (int) 0x0)
[    0.106085] CRIT: [libkvmplat] <traps.c @   84> Unhandled Trap 8 (double fault), error code=0x0
[    0.107422] CRIT: [libkvmplat] <trace.c @   41> RIP: 0000000000191281 CS: 0008
[    0.108532] CRIT: [libkvmplat] <trace.c @   42> RSP: 00000005fd410000 SS: 0010 EFLAGS: 00010202
[    0.109866] CRIT: [libkvmplat] <trace.c @   44> RAX: 0000000000000002 RBX: 0000000000191284 RCX: 00000000c0000100
[    0.111430] CRIT: [libkvmplat] <trace.c @   46> RDX: 0000000000000004 RSI: 00000005fd447018 RDI: 0000000400004018
[    0.112989] CRIT: [libkvmplat] <trace.c @   48> RBP: 0000000001afff70 R08: 0000000000199172 R09: 000000000019c319
[    0.114546] CRIT: [libkvmplat] <trace.c @   50> R10: 0000000000000000 R11: 0000000400001028 R12: 0000000400004018
[    0.116105] CRIT: [libkvmplat] <trace.c @   52> R13: 0000000000000001 R14: 0000000400000000 R15: 0000000400003020
[    0.117662] CRIT: [libkvmplat] <traps.c @   90> Crashing
Console terminated, terminating guest (PID: 465980)...
```

**Comment by StefanJum** [comment] 2023-03-08 12:45
Same as on #786, this can be reproduced by running a `helloworld` app with `lwip` enabled.

**Comment by marcrittinghaus** [comment] 2023-03-08 12:51
Ok, so it crashes in a simple helloworld app (no elfloader) if you use lwip or 9pfs?

**Comment by StefanJum** [comment] 2023-03-08 12:55
> Ok, so it crashes in a simple helloworld app (no elfloader) if you use lwip or 9pfs?

Yes, there may be more cases where it crashes, but these two were used by the `app-elfloader` so we stumbled upon them.

**Comment by marcrittinghaus** [comment] 2023-03-08 13:02
Yes, ok. Thanks for the info. Very strange though. Probably, we are just lucky in the other cases, and the problem exists universally. I might run into this issue myself sometime today. I'll provide info on what I find, in that case.

**Comment by marcrittinghaus** [comment] 2023-03-09 10:58
Ok, I know now what the problem is. Stacks are currently still allocated from the regular heap. However, with `ukvmem` the heap uses demand-paging. So not all pages of the stack are actually mapped. Now if you want to push something to the stack and the stack page is not mapped you get a page fault. So far so good. Problem is that currently, the traps are configured to use the current stack. Since this stack was the original reason for the page fault, pushing the exception frame onto the same stack does not work, too. This then leads to a double fault. Since the double fault uses a dedicated stack, jumping to it works and we see the crash message.

We should take the following measures to solve this:
Configure IST to use a dedicated stack also for regular traps. It also has the benefit of guaranteeing a working stack on a trap. Disadvantage is that you cannot use nested faults (e.g., use uknofault in an exception handler). To allow this nevertheless, @mschlumpp suggested to reconfigure the trap on entry to use the currently configured stack instead of IST.

In parallel, we should extend `uksched` to use `ukvmem` for stack allocation if available. This will allow us to pre-allocate the whole stack. Also we get a guard page to more easily identify stack overruns.

**Comment by andraprs** [comment] 2023-03-27 09:41
The  fix from PR https://github.com/unikraft/unikraft/pull/790 has been merged.

**Closed as completed by andraprs** 2023-03-27 09:41 UTC
Labels: kind/bug
