### ISSUE TITLE
Double fault at 9pfs mount when making elfloader with posix-mmap

### ISSUE THREAD

**Issue by John-Ted** [unikraft/unikraft#786] opened 2023-03-08 11:51 UTC
### Describe the bug

Double fault occuring in the elfloader app when mounting 9pfs, if the image was created using posix-mmap.

### Steps to reproduce

1. Create an elfloader image using posix-mmap.
2. Try to run an application in binary compat mode using the image created at step 1.

Example config:
[config.txt](https://github.com/unikraft/unikraft/files/10920230/config.txt)

### Expected behavior

The unikernel should boot, output the banner, enter the application's main function and any possible issues should arise due to the binary application, not the unikernel itself.

### Relevant log output

```shell
SeaBIOS (version 1.15.0-1)
Booting from ROM...
[    0.100029] dbg:  [libvfscore] <main.c @ 1990> (int) uk_syscall_r_dup2((int) 0x0, (int) 0x1)
[    0.101306] dbg:  [libvfscore] <main.c @ 1937> (int) uk_syscall_r_dup3((int) 0x0, (int) 0x1, (int) 0x0)
[    0.102711] dbg:  [libvfscore] <main.c @ 1990> (int) uk_syscall_r_dup2((int) 0x0, (int) 0x2)
[    0.103976] dbg:  [libvfscore] <main.c @ 1937> (int) uk_syscall_r_dup3((int) 0x0, (int) 0x2, (int) 0x0)
[    0.105901] dbg:  [libvfscore] <mount.c @  112> (int) uk_syscall_r_mount((const char*) 0x18143c, (const char*) 0x181776, (const char*) 0x17e636, (unsigned long) 0x0, (const void*) 0x1811a8)
[    0.108469] CRIT: [libkvmplat] <traps.c @   84> Unhandled Trap 8 (double fault), error code=0x0
[    0.109808] CRIT: [libkvmplat] <trace.c @   41> RIP: 00000000001764d1 CS: 0008
[    0.110884] CRIT: [libkvmplat] <trace.c @   42> RSP: 0000000400070000 SS: 0010 EFLAGS: 00010202
[    0.112172] CRIT: [libkvmplat] <trace.c @   44> RAX: 0000000000000002 RBX: 00000000001764d4 RCX: 00000000c0000100
[    0.113699] CRIT: [libkvmplat] <trace.c @   46> RDX: 0000000000000005 RSI: 00000004000030b0 RDI: 00000005fd459018
[    0.115226] CRIT: [libkvmplat] <trace.c @   48> RBP: 0000000001aecdd0 R08: 000000000017dcaa R09: 0000000000180e25
[    0.116750] CRIT: [libkvmplat] <trace.c @   50> R10: 0000000400004050 R11: 0000000000000001 R12: 0000000400008018
[    0.118276] CRIT: [libkvmplat] <trace.c @   52> R13: 00000005fd459018 R14: 0000000000000001 R15: 0000000000000008
[    0.119806] CRIT: [libkvmplat] <traps.c @   90> Crashing
Console terminated, terminating guest (PID: 461692)...
```

**Comment by StefanJum** [comment] 2023-03-08 12:09
@John-Ted You can reproduce this by simply running a `helloworld` application with `posix-mmap` enabled and a `9pfs` filesystem.
Should be easier to debug than running an app through the elfloader.

**Comment by marcrittinghaus** [comment] 2023-03-08 12:39
Hey guys, interesting finding that it also happens with helloworld if you use 9pfs. Maybe that is causing the problem. Have you tried ramfs? I only tested it with ramfs yet. Whereas the tests for `posix-mmap` are not really there yet, `ukvmem` has quite a bunch of tests. And these also test file mappings with ramfs.

**Comment by StefanJum** [comment] 2023-03-08 12:48
@marcrittinghaus everything seems to work fine with `ramfs`.

**Comment by StefanJum** [comment] 2023-03-08 16:33
I kept looking a bit into this.
It seems to break [here](https://github.com/unikraft/unikraft/blob/staging/arch/x86/x86_64/ctx.S#L92), in the `ukarch_ctx_switch`, on a `push [rsi]`, which is weird since `rsi` contains a valid address.
The backtrace is:

<details>

```
#0  ukarch_ctx_switch () at [...]unikraft/arch/x86/x86_64/ctx.S:82
#1  0x0000000000122e92 in uk_sched_yield ()
    at [...]unikraft/lib/uksched/include/uk/sched.h:107
#2  uk_9preq_waitreply (req=req@entry=0x403df0018)
    at [...]unikraft/lib/uk9p/9preq.c:189
#3  0x00000000001242ef in send_and_wait_zc (dev=0x403df4018, zc_dir=UK_9PREQ_ZCDIR_NONE,
    zc_buf=0x0, zc_size=0, zc_offset=0, req=0x403df0018)
    at [...]unikraft/lib/uk9p/9p.c:62
#4  send_and_wait_zc (zc_offset=0, zc_size=0, zc_buf=0x0, zc_dir=UK_9PREQ_ZCDIR_NONE,
    req=0x403df0018, dev=0x403df4018) at [...]unikraft/lib/uk9p/9p.c:48
#5  send_and_wait_no_zc (req=0x403df0018, dev=0x403df4018)
    at [...]unikraft/lib/uk9p/9p.c:72
#6  uk_9p_version (dev=0x403df4018, requested=<optimised out>, received=received@entry=0x1a6e80)
    at [...]unikraft/lib/uk9p/9p.c:106
#7  0x0000000000115abf in uk_9pfs_mount (mp=0x400014018, dev=0x14e9a8 "fs0", flags=<optimised out>,
    data=<optimised out>) at [...]unikraft/lib/9pfs/9pfs_vfsops.c:188
#8  0x0000000000139bd6 in __uk_syscall_r_mount (dev=0x14e9a8 "fs0", dir=dir@entry=0x14e770 "/",
    fsname=<optimised out>, flags=0, data=0x14e72a)
    at [...]unikraft/lib/vfscore/mount.c:219
#9  0x0000000000139ebd in uk_syscall_r_mount (data=<optimised out>, flags=<optimised out>,
    fsname=<optimised out>, dir=1369968, dev=<optimised out>)
    at [...]unikraft/lib/vfscore/mount.c:112
#10 uk_syscall_e_mount (data=<optimised out>, flags=<optimised out>, fsname=<optimised out>,
    dir=1369968, dev=<optimised out>) at [...]unikraft/lib/vfscore/mount.c:112
#11 mount (dev=<optimised out>, dir=dir@entry=0x14e770 "/", fsname=<optimised out>,
    flags=<optimised out>, data=<optimised out>)
    at [...]unikraft/lib/vfscore/mount.c:112
#12 0x000000000014a378 in vfscore_rootfs ()
    at [...]unikraft/lib/vfscore/rootfs.c:122
#13 0x0000000000129532 in ukplat_entry (argc=2, argv=argv@entry=0x190da0 <argv>)
    at [...]unikraft/lib/ukboot/boot.c:323
#14 0x000000000012975f in ukplat_entry_argp (arg0=arg0@entry=0x0, argb=<optimised out>,
    argb_len=<optimised out>) at [...]unikraft/lib/ukboot/boot.c:224
#15 0x000000000010f4ed in _ukplat_entry2 ()
    at [...]unikraft/plat/kvm/x86/setup.c:290
#16 0x0000000000000000 in ?? ()
```

</details>

Small update:
Seems like the crash happends after the stack switch because even if the new stack pointer is loaded, the address right above it (`$rsp - 8`, that would be accessed by a `push`) is not loaded (maybe it's paged-out?).

The problem looks very similar to the one that linux solves by adding a `READ_ONCE` [here](https://elixir.bootlin.com/linux/v4.14.67/source/arch/x86/include/asm/switch_to.h#L36).

Adding a `UK_READ_ONCE(*((unsigned char *)next->ctx.sp - 8))` [here](https://github.com/unikraft/unikraft/blob/staging/lib/uksched/include/uk/sched_impl.h#L103), before doing the actual context switch, fixes the issue, but using a usual `READ_ONCE(*((unsigned char *)next->ctx.sp))` without the `-8` still breaks (since, again, the actual stack pointer is loaded just fine).

**Comment by marcrittinghaus** [comment] 2023-03-09 10:59
See #787

**Comment by andraprs** [comment] 2023-03-27 09:40
The  fix from PR https://github.com/unikraft/unikraft/pull/790 has been merged.

**Closed as completed by andraprs** 2023-03-27 09:40 UTC
Labels: kind/bug
