### ISSUE TITLE
External bootloaders cannot boot the kernel

### ISSUE THREAD

**Issue by nekowink** [unikraft/unikraft#263] opened 2021-08-08 05:38 UTC
### Describe the bug

The helloworld demo can be successfullly built and booted by loading the kernel directly in QEMU:
```sh
sudo qemu-system-x86_64 -nographic -kernel /home/nekowink/app-helloworld/build/app-helloworld_kvm-x86_64
```

However, building a image with external bootloader seems to be buggy.
I have tried the following bootloaders (none of them worked):
- SYSLINUX (copying the settings from [GCP build script](https://github.com/unikraft/plat-gcp/blob/staging/scripts/deploy-unikraft-gcp.sh))
- GRUB2
- [STOOMBOOT](https://github.com/firebitsbr/stoomboot)

Using the image as the system image in Cloud VMs also replicated the problem (e.g. for images based on SYSLINUX, stuck in the `Loading unikernel.bin...` stage and reboot infinitely).

Want to know if the building instructions or something got wrong. Thanks!

-----
directly boot (ok):
<img width="571" alt="DIRECTLY" src="https://user-images.githubusercontent.com/47276239/128621463-68699892-88fa-48b4-9af4-584a12f58817.png">

grub2 (page fault):
<img width="571" alt="GRUB2" src="https://user-images.githubusercontent.com/47276239/128621331-6e8971b6-7fb2-4ae5-a5ab-1a14de54bb41.png">

syslinux (infinite reboot):
<img width="571" alt="SYSLINUX" src="https://user-images.githubusercontent.com/47276239/128621332-c39f5402-88f4-457f-979f-f61936612738.png">

### Steps to reproduce

**STEP1** Build:
```sh
kraft list update
kraft up -t helloworld ./app-helloworld
```

**STEP2** Then boot w/ qemu by loading the kernel direcly:
```sh
APP_DIR="/home/nekowink/app-helloworld"
sudo qemu-system-x86_64 -nographic -kernel $APP_DIR/build/app-helloworld_kvm-x86_64
```
Everything should run smoothly.

**STEP3** Build a SYSLINUX-based image:
The following commands have dependencies: syslinux, mkdosfs.
Also remember to **run them in root**.
```sh

SIZE=16
dd if=/dev/zero of=unikraft_syslinux.img bs=1M count=$SIZE
losetup /dev/loop0 unikraft_syslinux.img
loop=/dev/loop0

sudo parted $loop mklabel msdos
# ignore warnings
sudo parted -a optimal $loop mkpart primary 0% 100%
sudo parted $loop set 1 boot on

mkdosfs /dev/loop0p1
syslinux --install /dev/loop0p1

mkdir /loopfs
mount -o loop /dev/loop0p1 /loopfs

MBR="/usr/lib/syslinux/mbr/mbr.bin"
LIBCOM32="/usr/lib/syslinux/modules/bios/libcom32.c32"
MBOOT="/usr/lib/syslinux/modules/bios/mboot.c32"
UNIKERNEL="/home/nekowink/app-helloworld/build/app-helloworld_kvm-x86_64"

cp $LIBCOM32 /loopfs/libcom32.c32
cp $MBOOT /loopfs/mboot.c32
cp $UNIKERNEL /loopfs/unikernel.bin
cat <<EOM >/loopfs/syslinux.cfg
TIMEOUT 0
DEFAULT unikernel
LABEL unikernel
  KERNEL mboot.c32
  APPEND unikernel.bin
EOM
sync
umount -vd /loopfs
```

**STEP4** Run the image built in the last step:
```sh
sudo qemu-system-x86_64 -nographic unikraft_syslinux.img
```

------

**STEP3b** Build a GRUB2-based image:
Use a different way to create disk image.
Also remember to **run them in root**.
```sh

dd if=/dev/zero of=unikraft_grub2.img count=20 bs=1048576
parted --script unikraft_grub2.img mklabel msdos mkpart p ext2 1 20 set 1 boot on
kpartx -a unikraft_grub2.img

# sleep a sec, wait for kpartx to create the device nodes
sleep 1
mkfs.ext2 /dev/mapper/loop0p1
mkdir -p build/tmp/p1
 
mount /dev/mapper/loop0p1 build/tmp/p1
cp /home/nekowink/app-helloworld/build/app-helloworld_kvm-x86_64 build/tmp/p1/hi
echo "(hd0) /dev/loop0" > build/tmp/device.map

grub-install  --no-floppy                                                      \
              --grub-mkdevicemap=build/tmp/device.map                          \
              --modules="biosdisk part_msdos ext2 configfile normal multiboot" \
              --root-directory=build/tmp/p1                                    \
              /dev/loop0

umount build/tmp/p1
kpartx -d unikraft_grub2.img

```

**STEP4b** Run the image built in the last step:
```sh
sudo qemu-system-x86_64 -nographic unikraft_grub2.img
```
In GRUB2 shell, input the following command:
```sh
multiboot (hd0,msdos1)/hi
boot
```

### Expected behavior

Boot the kernel by a Multiboot-compliant bootloader successfully.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

**Comment by cristian-vijelie** [comment] 2021-08-09 06:35
Hi! Thanks for bringing this up. Before starting looking into the image creation itself, have you tried running Unikraft using kvm acceleration? If not, please try this, by using the "-enable-kvm -cpu host" options, and see if anything changes.

**Comment by nekowink** [comment] 2021-08-09 06:35
Perhaps the problem is somehow related to the issues #197 and #201..?
I will try to build a image from the commit [56943ad](https://github.com/unikraft/unikraft/commit/56943ad23981b201466ef9b9e983235b6cb3f0c8) and see if somethings changes.

**Comment by nekowink** [comment] 2021-08-09 06:38
> Hi! Thanks for bringing this up. Before starting looking into the image creation itself, have you tried running Unikraft using kvm acceleration? If not, please try this, by using the "-enable-kvm -cpu host" options, and see if anything changes.

Thanks for reply! Sorry I forgot to mention but w/ kvm acceleration the problem still exists.

**Comment by cristian-vijelie** [comment] 2021-08-09 07:05
Try this script. It uses grub-mkrescue to create the grub image.
```
#!/bin/bash

if [ ! -d "build/isofiles/" ]; then
    mkdir ./build/isofiles
    mkdir ./build/isofiles/boot
    mkdir ./build/isofiles/boot/grub
    printf "set default=0\nset timeout=0\n\nmenuentry \"Unikraft\" \
    {\n\tmultiboot -cdrom /boot/unikraft_kvm-x86_64\n\tboot\n}" \
    > ./build/isofiles/boot/grub/grub.cfg
fi

cp ./build/unikraft_kvm-x86_64 build/isofiles/boot/ && \
grub-mkrescue /usr/lib/grub/i386-pc -o \
./build/unikraft_kvm-x86_64.iso ./build/isofiles/ && \
sudo qemu-system-x86_64 -enable-kvm -m 128 \
-cpu host ./build/unikraft_kvm-x86_64.iso -serial stdio
```

It only runs the core unikraft image. You can adapt it to use the app-helloworld image. Also, you need to be in the main unikraft folder.

**Comment by nekowink** [comment] 2021-08-09 07:39
> Perhaps the problem is somehow related to the issues #197 and #201..?
> I will try to build a image from the commit [56943ad](https://github.com/unikraft/unikraft/commit/56943ad23981b201466ef9b9e983235b6cb3f0c8) and see if somethings changes.

Ahh I got wrong - the repo version `kraft` is current using is `RELEASE-0.5` and [56943ad](https://github.com/unikraft/unikraft/commit/56943ad23981b201466ef9b9e983235b6cb3f0c8) is just ahead of that.

**Comment by nekowink** [comment] 2021-08-09 07:42
> Try this script. It uses grub-mkrescue to create the grub image.
> 
> ```
> #!/bin/bash
> 
> if [ ! -d "build/isofiles/" ]; then
>     mkdir ./build/isofiles
>     mkdir ./build/isofiles/boot
>     mkdir ./build/isofiles/boot/grub
>     printf "set default=0\nset timeout=0\n\nmenuentry \"Unikraft\" \
>     {\n\tmultiboot -cdrom /boot/unikraft_kvm-x86_64\n\tboot\n}" \
>     > ./build/isofiles/boot/grub/grub.cfg
> fi
> 
> cp ./build/unikraft_kvm-x86_64 build/isofiles/boot/ && \
> grub-mkrescue /usr/lib/grub/i386-pc -o \
> ./build/unikraft_kvm-x86_64.iso ./build/isofiles/ && \
> sudo qemu-system-x86_64 -enable-kvm -m 128 \
> -cpu host ./build/unikraft_kvm-x86_64.iso -serial stdio
> ```
> 
> It only runs the core unikraft image. You can adapt it to use the app-helloworld image. Also, you need to be in the main unikraft folder.

The image created by grub-mkrescue worked magically! 
So something went wrong with other bootloaders.. Now I create a syslinux-based image in the following way:

```sh
#!/usr/bin/env bash
is_user_non_root () { [ "${EUID:-$(id -u)}" -ne 0 ]; }

if is_user_non_root; then
    echo "WARN: please run the script as ROOT." >&2
    exit 1
fi

WORKING_DIR="$(pwd)"
UNIKERNEL="$WORKING_DIR/build/bifrost_kvm-x86_64"
IMAGE_NAME="$WORKING_DIR/unikraft_syslinux_`date +%s`.img"
MBR="/usr/lib/syslinux/mbr/mbr.bin"
LIBCOM32="/usr/lib/syslinux/modules/bios/libcom32.c32"
MBOOT="/usr/lib/syslinux/modules/bios/mboot.c32"

dd if=/dev/zero of=$IMAGE_NAME bs=1M count=16
DISK="$(losetup -Pf --show $IMAGE_NAME)"
parted $DISK mklabel msdos
echo "[!] Input 'i' if you encounter a partition alignment warning."
parted -a optimal $DISK mkpart primary 0% 100%
parted $DISK set 1 boot on

mkdosfs ${DISK}p1
syslinux --install ${DISK}p1
mkdir /loopfs
mount -o loop ${DISK}p1 /loopfs

cp $LIBCOM32 /loopfs/libcom32.c32
cp $MBOOT /loopfs/mboot.c32
cp $UNIKERNEL /loopfs/unikernel.bin
cat <<EOM >/loopfs/syslinux.cfg
TIMEOUT 0
DEFAULT unikernel
LABEL unikernel
  KERNEL mboot.c32
  APPEND unikernel.bin
EOM

sync
umount -vd /loopfs
losetup -d $DISK
rm -rf /loopfs

echo
echo "--- Boot by kernel ---"
echo "sudo qemu-system-x86_64 -enable-kvm -m 128 \\"
echo "-cpu host --kernel ${UNIKERNEL} -serial stdio"
echo
echo "--- Boot by image ---"
echo "sudo qemu-system-x86_64 -enable-kvm -m 128 \\"
echo "-cpu host ${IMAGE_NAME} -serial stdio"
echo
```

**Comment by nekowink** [comment] 2021-08-09 07:46
Some artifacts that may help:

- `bifrost_kvm-x86_64`, a unikraft kernel built from app-helloworld (just changed the project name)
- `unikraft_syslinux_1628494620.img`, syslinux-based image built from the kernel

[kernel_and_disk_image.zip](https://github.com/unikraft/unikraft/files/6952765/kernel_and_disk_image.zip)

**Comment by cristian-vijelie** [comment] 2021-08-17 12:30
I consider the issue solved, as the problem was with how the image was built, not a bug in Unikraft.

However, in response to this issue, we will try to implement automatic generation of images, compatible with grub, or other bootloaders. Issue #265 was created to reference this. 

I will close it.

**Closed as completed by cristian-vijelie** 2021-08-17 12:30 UTC
Labels: kind/bug, plat/kvm, lib/ukboot, arch/x86_64, topic/booting, bug/runtime
